name = "web-file-sharing"
compatibility_date = "2024-05-01"

# Cloudflare Pages 读取的输出目录键名
pages_build_output_dir = ".vercel/output/static"

[vars]
# 在 Cloudflare Pages 控制台填充实际值。这里仅占位，避免意外暴露。
NODE_ENV = "production"

